=== NehalJain14/V2V-Automation-Testing/XML/EmployeeDetails.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT EmployeeDetails (Employee)*>
<!ELEMENT Employee (Employeecode, EmployeeName, DOJ, TotalExperience, Department, Designation, Salary, Grade)>
<!ELEMENT Employeecode (#PCDATA)>
<!ELEMENT EmployeeName (FirstName, LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT DOJ (#PCDATA)>
<!ELEMENT TotalExperience (#PCDATA)>
<!ELEMENT Department (Unit,Loc)>
<!ELEMENT Unit (#PCDATA)>
<!ELEMENT Loc (#PCDATA)>
<!ELEMENT Designation (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Grade (#PCDATA)>

=== NehalJain14/V2V-Automation-Testing/XML/EmployeeDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EmployeeDetails SYSTEM "EmployeeDetails.dtd">
<EmployeeDetails>
	<Employee>
		<Employeecode>emp-56789</Employeecode>
		<EmployeeName>
			<FirstName>Sakshi</FirstName>
			<LastName>Pandey</LastName>
		</EmployeeName>
		<DOJ>23/12/2025</DOJ>
		<TotalExperience>01 Years</TotalExperience>
		<Department>
		<Unit>4a</Unit>
		<Loc>Pune</Loc>
		</Department>
		<Designation>4</Designation>
		<Salary>30000</Salary>
		<Grade>b</Grade>
	</Employee>
		<Employee>
		<Employeecode>emp-1234</Employeecode>
		<EmployeeName>
			<FirstName>Rashi</FirstName>
			<LastName>Pandey</LastName>
		</EmployeeName>
		<DOJ>23/12/2025</DOJ>
		<TotalExperience>00</TotalExperience>
		<Department>
		<Unit>3a</Unit>
		<Loc>Mumbai</Loc>
		</Department>
		<Designation>4</Designation>
		<Salary>20000</Salary>
		<Grade>a</Grade>
	</Employee>
</EmployeeDetails>
